### ISSUE TITLE
Comparsion to RePod?

### ISSUE THREAD

**Issue by rugk** [pbek/nextcloud-nextpod#10]
Why should I use this app instead of _GePod_? Why is it better?
https://apps.nextcloud.com/apps/repod

Maybe add this to your Readme to clarify that? (Because as a new user, I am kinda confused by the variety of apps here, cf. https://github.com/AntennaPod/AntennaPod/issues/7244)

Also cross-posted/asked the other app/maintainer: https://git.crystalyx.net/Xefir/repod/issues/116

**Comment by pbek** [comment]
Hah, I didn't know about RePod... Looks like it was started this year.

And now we know: https://git.crystalyx.net/Xefir/repod#comparaison-with-similar-apps-for-nextcloud
😉

**Comment by rugk** [comment]
> not things RePod doesn't have 😉

…which are…? Better pitch your app here? :upside_down_face:

**Comment by pbek** [comment]
Well, you find most of that in https://github.com/pbek/nextcloud-nextpod/tree/main?tab=readme-ov-file#features.
