### ISSUE TITLE
Support Nexcloud 30

### ISSUE THREAD

**Issue by ximex** [pbek/nextcloud-nextpod#11]
Please update to support nextcloud 30

**Comment by pbek** [comment]
Haha, forgot that there was one more application I wrote. 😆 Thank you for the reminder.

**Comment by pbek** [comment]
## 0.7.6
- Updated and tested app for Nextcloud 30 (for [#11](https://github.com/pbek/nextcloud-nextpod/issues/11))

There now is a new release, could you please test it and report if it works for you?

**Comment by ximex** [comment]
i don't have nextcloud 30 yet, but it's not shown anymore as incompatible

**Comment by pbek** [comment]
> but it's not shown anymore as incompatible

That's just increasing to `max-version="30"` 😊 But I couldn't find anything else that breaks either...
