### ISSUE TITLE
Icon color doesn't  match with icons for other apps

### ISSUE THREAD

**Issue by arshubham** [pbek/nextcloud-nextpod#12]
Nextpod seems to use a muted white

![image](https://github.com/user-attachments/assets/30d8cd44-5518-4612-8ca2-da1fac098bbe)

![image](https://github.com/user-attachments/assets/2ab6b832-ada1-46ea-8026-9d3416a7e56b)

![image](https://github.com/user-attachments/assets/2916724b-459e-452a-8bf9-47e77a037056)

AIO v10.0.0 (Nextcloud 30.0.2)

**Comment by pbek** [comment]
## Next
- Removed opacity in app logo for better visibility in Nextcloud
  (for [#12](https://github.com/pbek/nextcloud-nextpod/issues/12))

Thank you. Will be part of the next release.

**Comment by pbek** [comment]
## 0.7.7
- Removed opacity in app logo for better visibility in Nextcloud
  (for [#12](https://github.com/pbek/nextcloud-nextpod/issues/12))

There now is a new release, could you please test it and report if it works for you?

**Comment by arshubham** [comment]
Can confirm. It is working as expected.

**Comment by pbek** [comment]
Great, thank you for testing!
Because for me, it still shows the opacity in my Nextcloud instance. 😂🤣

**Comment by arshubham** [comment]
It did for me after update. After a few reboots it was fixed. Might be some caching going on in browser
