### ISSUE TITLE
kein Kontenzugriff

### ISSUE THREAD

**Issue by cutec-chris** [pbek/nextcloud-nextpod#2]
Hallo erstmal, und Danke für die App ist nach gPodder Störungen genau das richtige.

Bin mir unsicher ob das mit Nextcloud oder der App zu tun hat, aber beim "Zugriff gewähren" seh ich nur den Ladekreis ewig. 
Wär toll falls da jemand ne idee hat.

**Comment by pbek** [comment]
English please. 😉 

Can you please describe what you expected, what the actual behavior was and step by step what you did?

**Comment by cutec-chris** [comment]
Hi ;)

ill try to connect to the app via Antennapod but this Screen:

![grafik](https://user-images.githubusercontent.com/5136391/226319194-ce692801-e807-4eec-a969-8649aa81e387.png)

stays there forever.

**Comment by pbek** [comment]
I will close this issue until there is more information.
