### ISSUE TITLE
[F] Audio player with start-time support

### ISSUE THREAD

**Issue by lazarusCantini** [pbek/nextcloud-nextpod#3]
Hey Patrizio,
thanks for this great piece of code, installed like a charm for me. I installed your software for the use-case of listening to my Podcast with synced progress with my android device (antenna pod) 
But exact this use case doesnt work. Is your software realy "only" able to view my podcasts, is it planed to add the synced listening feature or am I making it wrong?
Kindly regards,
Bastian

**Comment by pbek** [comment]
Thank you for your kind words!
The app already features a modal dialog where you can play an episode. Although browsers don't support a start-time for the used `<audio>` HTML tag. So unless I don't add a 3rd party JavaScript audio player you can only listen from the beginning.

**Comment by lazarusCantini** [comment]
Ok, thanks for your clearification. Are you thinking about working on this feature this year, or should i go on with my search?

**Comment by pbek** [comment]
Quite possibly when I find a good player supporting that and that works well with VueJs...
Maybe https://github.com/redxtech/vue-plyr... If you find one, please let me know.

**Comment by pbek** [comment]
## 0.5.0
- The episode player now automatically starts playing at the synced position

There now is a new release, could you please test it and report if it works for you?

**Comment by spiezmaestro** [comment]
This is brilliant. Thanks a lot!!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
I wonder if it would make sense to also store the updated time while playing... 🤔

**Comment by pbek** [comment]
Maybe a checkbox you need to check each time that should happen... I don't know.

**Comment by pbek** [comment]
## 0.6.0
- The play status is now optionally stored while playing an episode

There now is a new release, could you please test it and report if it works for you?

**Comment by lazarusCantini** [comment]
Installed, tested, works great! Thank you so much.

**Comment by pbek** [comment]
Great, thank you for testing, have fun! (And thank you for your donation! 😉 )
